### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by biscuitpants** [SinZ163/TEvE-2#23]
I am willing to help if need be. I can test / mod? I am a programmer (Swift and C#) but can try my hand at Dota 2 maps.

**Comment by AlexSem98** [comment]
hi man yea we need some help what's your name on steam?

**Comment by biscuitpants** [comment]
pussypantsguy

My profile image is a man wearing weird shorts.

**Comment by AlexSem98** [comment]
i tried to find you but i couldn't find you if you can add me on steam ertin362 or Mr.Simenius

**Comment by MNoya** [comment]
Do you guys know you can just copy the link to your steam profile right?

Such as: http://steamcommunity.com/id/mnoya

**Comment by biscuitpants** [comment]
@AlexSem98 I've added you
